### ISSUE TITLE
Fermeture de la modale

### ISSUE THREAD

**Issue by ErickTraore** [OpenClassrooms-Student-Center/GameOn-website-FR#283]
Utilisation de: "display = none" pour fermer la modale.

**Comment by DamienL47** [comment]
Je crois qu'il y à eu erreur là non ? il faudrait clôturer cette issue si elle n'a rien à faire dans le cours car cela pourrait induire en erreur d'autres étudiants !

**Comment by Keirodev** [comment]
> Utilisation de: "display = none" pour fermer la modale.

@ErickTraore Peux-tu supprimer / clore ton issue stp ?

**Comment by lucbourrat** [comment]
undesirable issue
